language: node_js
node_js:
- '0.10'
before_install:
- npm install -g gulp
script:
- npm run build
after_success:
- cd dist
- git config --global user.name "Travis Buildsson"
- git config --global user.email "travis@jivaro.com"
- git add *
- git commit -am "Travis CI"
- git push origin master