language: node_js
node_js:
- '0.10'
branches:
  only:
    - master
before_install:
- npm install -g gulp
- npm install
before_script:
- git config --global user.name ${GIT_NAME}
- git config --global user.email ${GIT_EMAIL}
- echo git remote origin
- git remote rm origin
- git remote add origin https://haukurmar:${GH_TOKEN}@github.com/haukurmar/travis-ci.git

script:
- npm run build

after_success:
- ls
- git commit -am "Dist build by Travis-CI build number: ${TRAVIS_BUILD_NUMBER}"
- git push origin HEAD:master

env:
  global:
  - secure: E0u+PlB8gs8aALOJEf5IX5qqElFfOWLBdKR4+7XoNddKWtJyozRX8HSXeUW8SqXuBMWqBCtcwMBVSXrldYeOU0BBFHk2D0F3OY9i/rTVA6xp+mbJojhGvJyIw6uvHU0cjHTr3qOdXHY4reNHPsSBZkyIO8tLTwXy/UkpqNfduDCymDJVNfpQNnJ5nH9XJn1hf2HWYPZynZodG1/qoVvBWSlsrtb2+Lk51PkO2WfHyMy7ozFjUUX0bkPJ2fvre+ic4HGHlD/+OUTMVE5Az6FoWMLFZ/sxb5FTpq12FG7DIwuZUthRXdPfDTZUSM2tuf/JxW2y6x/jlntbsbtiWxcdgirP5HqW8zaf/SgEWVDQgQli09w71jEHyJHiEZHgND3w6k/EUvqM5kA+72xCi00QGOZmlXjrK/1WTnSukKetHZ4V9Q1+H+BU846/VHYu4GzSAiCn8uHjelmtXtzUyg5eXowEeVAnW4XNGx8UbFZcMQ+pUjiy3WcwY3cdr11esWv2jJDdd8CkNKqJ9PqdQOE+DJsmWhtQ/ma1fqNrxKL2bgOW/sXBeH0lWcnDKGvDfnE9zpTSlGU3xokWvtbVukOYdqL++bGdGGlVTqo3bxVX7Gy4ZTKvoKBdZb4wk6roNYDRPVRWUVmeOYxGQfxyD8GmSzKS8C8pkqSHSDlw6pzHBM4=
  - secure: Kfp2WTM0fkEvbe6JQAWwV/4dEVzjdZKLlF0KAVs5tL3QbY5vixsA/R1IuCz89edTxnGkpbDqLk/6zW763HjPAnnynWZONbBvnzXdR/0FWPCHP3ouUI4l4mrQ/30aIdSKngZ3d8SbuKa/qmSTPMrLc7cqyiZWqvqcKxTg9HXavfa/JWtnQlEjVCoc3RxC7gMuVEbkBCc2pZNynz8LOKT2m7tVLpkurDil561tcsTLbosu6KcSRxXZ8m0LToyk0cRn9foS/E+wXr37LXwDxmyGSAusd/1GtkwgBmeteFra8k+pL/gWGMAMI8RGWKA8mDN/QaD+ZO7egO2wxNchuFQWvyfBozATjZ0TK8ucHi6LVE+Zeo2krOCwAypfm5/WNOZwd5qGOpZnlHQUOPhYEybSlBQau2BizG/2FpOHNeg5A4IXZgYRiIv94HJWT3QwF+sG7BuP4CUDUXRUKBI+A7D8g9qDBcUVGUGx3b0xRe7KW4JqdCz1kaG1yT9G3QXBkBzIXRYocGJkZ7kc80vpUbL/HnUcJf6Fwj1i3utAwNndRlh/lLQNPYEdbthujIXkhziNLLuRspkMFpDEXHsL3w6YdGCVtHhHu0k5KHiTpUDCfveVnwVmIr+WKkbJmEmfA0da3hgQ0lmC48yZsi5XFVCWwAaUQUlY9E9Bq4/Sx2Dzw4M=
  - secure: GBGtKhvwJ8XWVV1NkI1uyHYGace1piiNUnC+UTGGcZCye6XgdDTdTCY+ROIIhPPEYEqtq9IhdxGebYIpTX4VOhCMbNDIhlFKHW1mCsRijbXmMcd0VImBEEXZlfA8d/yr3gG02+QE0lQyeTnV7dH6s1rtDXed7JYIKmPJHrIXzEOHDoR8UBEUQ1tnYBOhieqwPfJLpEkNlXqZ21WSPQIXJABI7EjQr+ehjiZ6gfaNgQZSurHc6Rl0U3j1Q9AotwPHpSIV/zjjecL18sZteyv1C6g2o1BSrmX5N0Tjn1tpXbXPGyO1yZrVr0GK/tQlxYP7kfICUOcQLFkzguNRCkTLuRVB/tONLn7Cx5DrPf8t3dYi4j5fEbKIgB72MuLZlvEyzl8zkhsGlJeaJ74k4jQiq200LDuosjuOqTuz9Qu2b/h233JCQ845N12n81UDLEfII6c50+CRHMWHdGx0WGJVKJMB6s8jO5zJO6FVUrAXzf3foNU47sLi/E3YmWUzzGN0Njf9ELG7UQHCU4dpTjlrGRv4pf9E4MdAXU2g2ODHAHIQId+ZO68cewBzPeHe/J58wiXJ+w0HMOiCLx+WbKv5hLk5+DWyZmmaUJEdNK1DEmjawHhhtKwnf4PCExTijy+uLSt8kHiN8JYHaHlUBYksPeA3x/CaOWQnngoN2q6+s9Q=
