language: node_js
node_js:
- '0.10'
before_install:
- npm install -g gulp
script:
- npm run build
after_success:
- cd dist
- git config --global user.name "Haukur Már Böðvarsson"
- git config --global user.email "haukurmar@gmail.com"
- git add .
- git commit -am "Travis CI"
- git push "https://${GH_TOKEN}@${GH_REF}" origin master